### ISSUE TITLE
Is there a way to get parent goroutine id?

### ISSUE THREAD

**Issue by kedebug** [jtolds/gls#10]
For passing trace context, only current `gls` is not enough, is there a way to get parent goroutine id? So we can get parent trace context.

**Comment by jtolds** [comment]
Oh oh, if you're doing traces, you should have a span id, parent span id, and trace id all be separate concepts from the goroutine id. I would recommend using (contexts, actually, but if you must) gls to store a current *Span struct, and then whenever you start a new span, look at the current *Span to get the parent. 

To answer your question directly, we could change gls to store the parent goroutine id, but it would require that everyone use gls.Go instead of the go keyword for it to work. 

If you're looking into traces, I spent a lot of time making the monkit API useful and extensible for tracing libraries. They do require contexts though. See https://github.com/spacemonkeygo/monkit and https://github.com/spacemonkeygo/monkit-zipkin for examples.
