### ISSUE TITLE
please tag and version this project

### ISSUE THREAD

**Issue by aviau** [jtolds/gls#4]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for gls and versioning would help Debian keep up with development.

**Comment by jtolds** [comment]
Absolutely! https://github.com/jtolds/gls/releases/tag/v4.2.0

Would it help you at all to keep the debian packaging upstream?

Incidentally, I do a bunch of debian packaging myself (not for Debian, but for $dayjob). Is https://pkg-go.alioth.debian.org/packaging.html the latest advice? I'm wondering because Go 1.6 now supports generating shared libraries on a number of architectures.

**Comment by aviau** [comment]
Thank you!

We prefer to keep packaging outside of the upstream repository. The [upstream guide](https://wiki.debian.org/UpstreamGuide) even asks that you don't include a ```debian``` folder in your repository.

```jtolds/gls``` is already packaged in Debian. See [here](https://tracker.debian.org/pkg/golang-github-jtolds-gls).

We don't generate shared libraries yet, but we probably will do it in the future.

The guide you found is the correct policy. I maintain ```jtolds/gls``` as part of the Go Packaging Team on Alioth:
 - ```https://anonscm.debian.org/git/pkg-go/packages/golang-github-jtolds-gls.git```
